### ISSUE TITLE
tensorflow  libcudnn version mismatch

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/container-jupyter-nvidia#11]
For some reason tensorflow 2.8.0 is being installed in the image. Even though we specify [2.3.1](https://github.com/radiasoft/download/blob/fba7f4a1d31de43fde52d6d56b946b8d3052fb2e/installers/rpm-code/codes/ml.sh#L38)

```bash
tensorflow (master)$ docker run -it --rm radiasoft/jupyter-nvidia:prod /bin/bash -c '/home/vagrant/.pyenv/shims/pip list | grep "tensorflow\s"'
tensorflow                      2.8.0
```

Sirepo doen't have this problem so it is probably something specific to this image
```bash
tensorflow (master)$ docker run -it --rm radiasoft/sirepo:prod /bin/bash -c '/home/vagrant/.pyenv/shims/pip list | grep "tensorflow\s"'
tensorflow                      2.3.1
```

Need to be careful that all versions work with eachother https://www.tensorflow.org/install/source#gpu

**Comment by e-carlin** [comment]
Well this is why it is at 2.8.0 https://github.com/radiasoft/container-jupyter-nvidia/blob/012b40b6fc2cef8595759b5eded5e4df1b8551e0/container-conf/build.sh#L33

I'm going to pin to 2.8.0 and then make sure that the cuda versions match

**Comment by mkilpatr** [comment]
Project: nuline
I'm getting a simmilar issue with cuDNN library incompatibility. I initially use the default version of tensorflow (2.8.0) and everything is fine up until the `model.fit` stage, when I encounter a library incompatibility. The error output is below (I left out the traceback for readability, but I can include it if necessary). I have a work around for this by installing tensorflow 2.4.0 which has the correct version of cuDNN. Once I have this new version I can then re-run all the cells, but then I get to an error finding the GPU. A peculiar thing is that after I have this new version I cannot restart the kernel because it doesn’t have the required keras libraries. 
```
2022-04-08 16:49:17.817880: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-04-08 16:49:17.819522: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
```

**Comment by mkilpatr** [comment]
This is preventing any GPU training with the ML methods. I can confirm working code with the CPU though. Not urgent, but would be good to have soon.

**Comment by e-carlin** [comment]
@mkilpatr the script you gave me ran successfully with the update. Please confirm it works for you.

**Comment by mkilpatr** [comment]
Thank you @e-carlin. The update works for me on the file I gave you and on the more complicated implementation of the model. Looks like all is well!
